snowflake:
  account: "your-account.snowflakecomputing.com"
  user: "your-username"
  password: "your-password"
  warehouse: "COMPUTE_WH"
  database: "GEOCHAT_DB"
  schema: "AI_SCHEMA"
  role: "PUBLIC"
